platform :ios, "7.0"

pod "SocketRocket"
pod "GoogleSignIn"
pod "Google"

source "https://github.com/CocoaPods/Specs.git"
platform :ios, "8.0"
use_frameworks!

pod "Socket.IO-Client-Swift", "~> 4.1.1" # Or latest version
